# Exceptions

Exceptions used by the project.

[Handsdown API Index](../README.md#handsdown-api-index) / [Handsdown](./index.md#handsdown) / Exceptions

> Auto-generated documentation for [handsdown.exceptions](https://github.com/vemel/handsdown/blob/main/handsdown/exceptions.py) module.

## GeneratorError

[Show source in exceptions.py:6](https://github.com/vemel/handsdown/blob/main/handsdown/exceptions.py#L6)

Main error for `BaseGenerator`.

#### Signature

```python
class GeneratorError(Exception):
    ...
```



## ImportStringError

[Show source in exceptions.py:18](https://github.com/vemel/handsdown/blob/main/handsdown/exceptions.py#L18)

Main error for `ImportString`.

#### Signature

```python
class ImportStringError(Exception):
    ...
```



## LoaderError

[Show source in exceptions.py:12](https://github.com/vemel/handsdown/blob/main/handsdown/exceptions.py#L12)

Main error for `Loader`.

#### Signature

```python
class LoaderError(Exception):
    ...
```



## ParserError

[Show source in exceptions.py:30](https://github.com/vemel/handsdown/blob/main/handsdown/exceptions.py#L30)

Main error for source code parsing issues.

#### Signature

```python
class ParserError(Exception):
    ...
```



## PathFinderError

[Show source in exceptions.py:24](https://github.com/vemel/handsdown/blob/main/handsdown/exceptions.py#L24)

Main error for `PathFinder`.

#### Signature

```python
class PathFinderError(Exception):
    ...
```
